name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        working-directory: plugin
        run: ./gradlew build
      - name: Test composite build
        working-directory: tests/composite-build/subproject3
        run: ./gradlew packageFatCapsule
      - name: Test Kotlin DSL build
        working-directory: tests/kotlin-dsl
        run: ./gradlew packageFatCapsule
      - name: Test Groovy DSL build
        working-directory: tests/groovy-dsl
        run: ./gradlew packageFatCapsule
